solon.app.name: helloapp

solon.cloud:
  discovery:
    server: 172.168.0.48:8848
    username: nacos
    password: nacos
  config:
    server: 172.168.0.48:8848
    username: nacos
    password: nacos