solon.app:
  group: "water"
  name: "demo10api"

solon.cloud.water:
  server: "water"
  config:
    loadGroup: "water"
    loadKey: "*"
  event:
    seal: "0zJt0J88TkIvqYgC"
  log:
    default: "water_api_log"